# Generated by Django 5.2.1 on 2025-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_frame', models.CharField(choices=[('5 minute', '5 minute'), ('15 minute', '15 minute'), ('30 minute', '30 minute'), ('1 hour', '1 hour')], max_length=20)),
                ('quantity', models.FloatField()),
                ('broker', models.CharField(choices=[('Exness', 'Exness'), ('IC Markets', 'IC Markets'), ('OANDA', 'OANDA'), ('XM', 'XM')], max_length=50)),
                ('strategy', models.CharField(choices=[('EMA High Low Strategy', 'EMA High Low Strategy'), ('MACD Crossover', 'MACD Crossover'), ('Bollinger Bands', 'Bollinger Bands'), ('RSI Reversal', 'RSI Reversal')], max_length=50)),
                ('exit_type', models.CharField(choices=[('Exit By Signal', 'Exit By Signal'), ('Exit By Target', 'Exit By Target'), ('Exit By Stoploss', 'Exit By Stoploss')], max_length=30)),
                ('index', models.CharField(choices=[('XAUUSD', 'XAUUSD'), ('BTCUSD', 'BTCUSD'), ('US30', 'US30'), ('ETHUSD', 'ETHUSD')], max_length=10)),
                ('target', models.FloatField()),
                ('stoploss', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
