# Generated by Django 5.2.1 on 2025-07-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botconfiguration',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='broker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='exit_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='index',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='strategy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='time_frame',
            field=models.CharField(max_length=50),
        ),
    ]
