# Generated by Django 5.2.1 on 2025-07-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_rename_last_updated_botconfiguration_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botconfiguration',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='broker',
            field=models.CharField(choices=[('Exness', 'Exness'), ('IC Markets', 'IC Markets'), ('OANDA', 'OANDA'), ('XM', 'XM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='exit_type',
            field=models.CharField(choices=[('Exit By Signal', 'Exit By Signal'), ('Exit By Target', 'Exit By Target'), ('Exit By Stoploss', 'Exit By Stoploss')], max_length=30),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='index',
            field=models.CharField(choices=[('XAUUSD', 'XAUUSD'), ('BTCUSD', 'BTCUSD'), ('US30', 'US30'), ('ETHUSD', 'ETHUSD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='strategy',
            field=models.CharField(choices=[('EMA High Low Strategy', 'EMA High Low Strategy'), ('MACD Crossover', 'MACD Crossover'), ('Bollinger Bands', 'Bollinger Bands'), ('RSI Reversal', 'RSI Reversal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='time_frame',
            field=models.CharField(choices=[('5 minute', '5 minute'), ('15 minute', '15 minute'), ('30 minute', '30 minute'), ('1 hour', '1 hour')], max_length=20),
        ),
    ]
