# Generated by Django 5.2.1 on 2025-07-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_rename_updated_at_botconfiguration_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfiguration',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
