# Generated by Django 5.2.1 on 2025-08-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_alter_botconfiguration_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botconfiguration",
            name="broker",
            field=models.CharField(
                choices=[
                    ("Angle one", "Angle one"),
                    ("Exness", "Exness"),
                    ("IC Markets", "IC Markets"),
                    ("OANDA", "OANDA"),
                    ("XM", "XM"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="botconfiguration",
            name="index",
            field=models.CharField(
                choices=[
                    ("NSE NIFTY 50", "NSE NIFTY 50"),
                    ("BANKNIFTY", "BANKNIFTY"),
                    ("Tata", "Tata"),
                    ("WIPRO", "WIPRO"),
                    ("RELIANCE", "RELIANCE"),
                    ("XAUUSD", "XAUUSD"),
                    ("BTCUSD", "BTCUSD"),
                    ("US30", "US30"),
                    ("ETHUSD", "ETHUSD"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="botconfiguration",
            name="time_frame",
            field=models.CharField(
                choices=[
                    ("1m", "1 minute"),
                    ("5 minute", "5 minute"),
                    ("15 minute", "15 minute"),
                    ("30 minute", "30 minute"),
                    ("1 hour", "1 hour"),
                ],
                max_length=20,
            ),
        ),
    ]
